#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "Running lint check"
output=$(golint pkg/... cmd/...)
if [ -z "$output" ]
then
    echo "Lint passed!"
else
    echo "$output"
    echo "LINT FAILED!"
    exit 1
fi

echo "Checking dependency"
output=$(grep replace go.mod)
if [ -n "$output" ]
then
    echo "Failed: found using local module"
    exit 1
else
    echo "Passed dep check"
fi
